table dim_abschluss
	lineageTag: 3af31ea3-77be-4cb4-9ce9-83875b529feb

	measure 'Quote ohne HSA %' = DIVIDE(CALCULATE(SUM(fact_abgaenge[anzahl]),fact_abgaenge[geschlecht]="insgesamt",dim_abschluss[abschluss_key]="ohne_hauptschulabschluss"),CALCULATE(SUM(fact_abgaenge[anzahl]),fact_abgaenge[geschlecht]="insgesamt"))*100
		lineageTag: 92e62e4a-2468-44c4-84a7-4f3e7daab8ae

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Abgänge = CALCULATE(SUM(fact_abgaenge[anzahl]),fact_abgaenge[geschlecht]="insgesamt")
		formatString: 0
		lineageTag: e4d25b08-3642-497d-b463-536a945a6faf

	measure 'Abgänge ohne HSA' = CALCULATE([Abgänge],dim_abschluss[abschluss_key]="ohne_hauptschulabschluss")
		formatString: 0
		lineageTag: cc4cedc1-c00b-460f-a7ca-35ca9d5458b0

	measure 'Abiturquote %' = DIVIDE(CALCULATE([Abgänge],dim_abschluss[abschluss_key]="allgemeine_hochschulreife"),[Abgänge])*100
		lineageTag: 7164655c-57fa-47d1-8d76-390bad571f3a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quote ohne HSA (Geschlecht) %' = DIVIDE(CALCULATE(SUM(fact_abgaenge[anzahl]),dim_abschluss[abschluss_key]="ohne_hauptschulabschluss"),CALCULATE(SUM(fact_abgaenge[anzahl])))*100
		lineageTag: cc801709-45ab-4e0d-9917-42af893885ab

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Abiturquote (Geschlecht) %' = DIVIDE(CALCULATE(SUM(fact_abgaenge[anzahl]),dim_abschluss[abschluss_key]="allgemeine_hochschulreife"),CALCULATE(SUM(fact_abgaenge[anzahl])))*100
		lineageTag: 0896443b-85db-453c-ad82-37b248606067

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Schüleranteil %' = DIVIDE(SUM(fact_schule_2023[schueler_insg]),CALCULATE(SUM(fact_schule_2023[schueler_insg]),ALL(dim_schulart),dim_schulart[schulart]<>"Insgesamt"))*100
		lineageTag: 07e732d5-729a-4e84-b902-2f075453e5f3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bev 15-18' = CALCULATE(SUM(fact_bevoelkerung_2023_2024[insgesamt]),fact_bevoelkerung_2023_2024[altersgruppe]="15 bis unter 18 Jahre",fact_bevoelkerung_2023_2024[jahr]=2023)
		formatString: 0
		lineageTag: db77f906-1a80-46e8-aa61-bca200899374

	measure 'Ohne HSA je 1000 (15-18)' = DIVIDE([Abgänge ohne HSA],[Bev 15-18])*1000
		lineageTag: 3cdc6de5-6abe-41ae-ac63-ccfa6e33d15a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ausgaben je Schüler Ø' = AVERAGE(fact_ausgaben_je_schueler[ausgaben_je_schueler])
		lineageTag: 51c82ecf-93f6-4430-b011-bf628e8760cf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Jugend-ALQ Ø' = AVERAGE(fact_arbeitsmarkt_2025[jugend_alq_15_25])
		lineageTag: f192af56-bae5-418e-ad4c-e5717a60778b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ausgaben je Schüler (Schulart) Ø' = AVERAGE(fact_ausgaben_schulart[ausgaben_je_schueler])
		formatString: 0
		lineageTag: 51c82ecf-93f6-4430-b011-bf628e8760d2

	measure 'Ausgaben Schulart (DE 2023)' = IF(ISFILTERED(dim_region[Land]) || ISFILTERED(fact_ausgaben_schulart[bundesland]), CALCULATE(AVERAGE(fact_ausgaben_schulart[ausgaben_je_schueler]), fact_ausgaben_schulart[jahr]=2023), CALCULATE(AVERAGE(fact_ausgaben_schulart[ausgaben_je_schueler]), fact_ausgaben_schulart[jahr]=2023, fact_ausgaben_schulart[bundesland]="Deutschland"))
		lineageTag: 0a0a87fc-6f26-4366-9dc2-9db470c94620

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ausgaben je Schüler (2023)' = CALCULATE(AVERAGE(fact_ausgaben_je_schueler[ausgaben_je_schueler]),fact_ausgaben_je_schueler[jahr]=2023)
		lineageTag: f56088ea-f594-44d7-912e-da8d5d5171d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Risiko-Score = VAR pop = CALCULATETABLE(ADDCOLUMNS(FILTER(VALUES(dim_region[region_code]),NOT ISBLANK([Quote ohne HSA %])&&NOT ISBLANK([Jugend-ALQ Ø])&&NOT ISBLANK([Verf. Einkommen je EW Ø])),"@q",[Quote ohne HSA %],"@a",[Jugend-ALQ Ø],"@e",[Verf. Einkommen je EW Ø]),REMOVEFILTERS(dim_region),REMOVEFILTERS(fact_einkommen_kreis),dim_region[ebene]="KR") VAR muQ=AVERAGEX(pop,[@q]) VAR sdQ=STDEVX.S(pop,[@q]) VAR muA=AVERAGEX(pop,[@a]) VAR sdA=STDEVX.S(pop,[@a]) VAR muE=AVERAGEX(pop,[@e]) VAR sdE=STDEVX.S(pop,[@e]) RETURN DIVIDE([Quote ohne HSA %]-muQ,sdQ)+DIVIDE([Jugend-ALQ Ø]-muA,sdA)+DIVIDE(muE-[Verf. Einkommen je EW Ø],sdE)
		lineageTag: a0ec6bf6-1f55-4983-8a0a-2c2034d8dcf1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'StdAbw Quote ohne HSA (Kreise)' = VAR bl = SELECTEDVALUE(dim_region[bundesland_code]) RETURN STDEVX.S(CALCULATETABLE(VALUES(dim_region[region_code]),REMOVEFILTERS(dim_region),dim_region[ebene]="KR",dim_region[bundesland_code]=bl),[Quote ohne HSA %])
		lineageTag: 54805988-4eb4-4a0e-886a-fb163634c902

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Verf. Einkommen je EW Ø' = AVERAGE(fact_einkommen_kreis[einkommen_je_ew])
		lineageTag: 9ad6d82d-97dc-467c-8b88-f1311a0c549b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Schüleranteil je Schulart, Basis nur abschlussvergebende weiterführende Schulen (ohne Grundschulen) – Fokus LF5
	measure 'Schüleranteil ohne Grundschule %' = DIVIDE(SUM(fact_schule_2023[schueler_insg]),CALCULATE(SUM(fact_schule_2023[schueler_insg]),ALL(dim_schulart),dim_schulart[schulart]<>"Insgesamt",dim_schulart[schulart]<>"Grundschulen"))*100
		lineageTag: b2b2b2b2-0005-4005-8005-000000000005

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Formatierungs-Measure (nicht analytisch): faerbt in LF1 den fuehrenden Balken
	/// Sachsen-Anhalt vermillion (#D55E00), die uebrigen gedaempft blau (#8C8C8C).
	measure 'Farbe Führung LF1' = IF(SELECTEDVALUE(dim_region[region]) = "Sachsen-Anhalt", "#D55E00", "#8C8C8C")
		lineageTag: b1f0c0de-1a2b-4c3d-9e8f-000000000f01

	/// LF4: Geschlechter-Gap ohne Hauptschulabschluss in Prozentpunkten (Jungen minus Maedchen), DE 2023 via Visual-Filter
	measure 'Gap ohne HSA (pp)' = CALCULATE([Quote ohne HSA (Geschlecht) %], fact_abgaenge[geschlecht]="maennlich") - CALCULATE([Quote ohne HSA (Geschlecht) %], fact_abgaenge[geschlecht]="weiblich")
		formatString: 0.0
		lineageTag: b1f0c0de-1a2b-4c3d-9e8f-000000000f02

	/// LF4: Geschlechter-Gap beim Abitur in Prozentpunkten (Maedchen minus Jungen), DE 2023 via Visual-Filter
	measure 'Gap Abitur (pp)' = CALCULATE([Abiturquote (Geschlecht) %], fact_abgaenge[geschlecht]="weiblich") - CALCULATE([Abiturquote (Geschlecht) %], fact_abgaenge[geschlecht]="maennlich")
		formatString: 0.0
		lineageTag: b1f0c0de-1a2b-4c3d-9e8f-000000000f03

	/// Formatierungs-Measure: LF9-Scatter, Top-10-Risiko-Kreise vermillion (Score >= 5,5 trennt exakt Platz 10 [5,57] von Platz 11 [5,44]), Rest gedaempft
	measure 'Farbe Risiko LF9' = IF([Risiko-Score] >= 5.5, "#D55E00", "#8C8C8C")
		lineageTag: b1f0c0de-1a2b-4c3d-9e8f-000000000f04

	/// Formatierungs-Measure: LF2-Top-15-Balken, Spitzenreiter Anhalt-Bitterfeld akzentuiert
	measure 'Farbe Hotspot LF2' = IF(SELECTEDVALUE(dim_region[region]) = "Anhalt-Bitterfeld, Landkreis", "#D55E00", "#8C8C8C")
		lineageTag: b1f0c0de-1a2b-4c3d-9e8f-000000000f05

	/// Formatierungs-Measure: LF5 linkes Diagramm, tragender Balken Grundschulen akzentuiert
	measure 'Farbe Schulart LF5' = IF(SELECTEDVALUE(dim_schulart[schulart]) = "Grundschulen", "#D55E00", "#8C8C8C")
		lineageTag: b1f0c0de-1a2b-4c3d-9e8f-000000000f06

	/// Formatierungs-Measure: LF5 rechtes Diagramm (ohne Grundschulen), tragender Balken Gymnasien akzentuiert
	measure 'Farbe Schulart LF5 oG' = IF(SELECTEDVALUE(dim_schulart[schulart]) = "Gymnasien", "#D55E00", "#8C8C8C")
		lineageTag: b1f0c0de-1a2b-4c3d-9e8f-000000000f07

	/// Formatierungs-Measure: LF6 Rangwechsel-Story - Sachsen-Anhalt vermillion, NRW Okabe-Ito-Blau, Rest grau (in beiden Charts)
	measure 'Farbe Rangwechsel LF6' = SWITCH(SELECTEDVALUE(dim_region[region]), "Sachsen-Anhalt", "#D55E00", "Nordrhein-Westfalen", "#0072B2", "#8C8C8C")
		lineageTag: b1f0c0de-1a2b-4c3d-9e8f-000000000f08

	/// Formatierungs-Measure: LF7 BL-Chart, Spitzenreiter Berlin akzentuiert
	measure 'Farbe Spitze LF7' = IF(SELECTEDVALUE(dim_region[Land]) = "Berlin", "#D55E00", "#8C8C8C")
		lineageTag: b1f0c0de-1a2b-4c3d-9e8f-000000000f09

	/// Formatierungs-Measure: LF7 Schulart-Chart, guenstigste Schulart Grundschulen akzentuiert
	measure 'Farbe Schulart LF7' = IF(SELECTEDVALUE(fact_ausgaben_schulart[schulart]) = "Grundschulen", "#D55E00", "#8C8C8C")
		lineageTag: b1f0c0de-1a2b-4c3d-9e8f-000000000f10

	/// Formatierungs-Measure: LF3-Scatter, die im Text belegten Rheinland-Pfalz-Kreise (bundesland_code 07) vermillion, uebrige neutral
	measure 'Farbe Streuung LF3' = IF(SELECTEDVALUE(dim_region[bundesland_code]) = "07", "#D55E00", "#8C8C8C")
		lineageTag: b1f0c0de-1a2b-4c3d-9e8f-000000000f11

	/// LF3/LF9 Dot-Plot: numerische X-Position des Bundeslands (1..16) aus dem AGS-Praefix bundesland_code,
	/// damit der native Scatter je Land eine Wertachse zeichnet (ein Punkt je Kreis, vertikale Streuung je Land sichtbar).
	measure BL-Position = VAR c = SELECTEDVALUE(dim_region[bundesland_code]) RETURN IF(NOT ISBLANK(c) && LEN(c) = 2, VALUE(c))
		formatString: 0
		lineageTag: b1f0c0de-1a2b-4c3d-9e8f-000000000f12

	/// LF5 (korrekte Antwort auf REQ-014): Abgaenge ohne Hauptschulabschluss je Schulart (Destatis 21111-12, Landesebene 2023).
	/// Ohne Land-Filter Default Deutschland (kein Doppelzaehlen ueber Land+DG), mit Land-Filter der jeweilige Landeswert.
	measure 'Abgänge ohne HSA (Schulart)' = IF(ISFILTERED(dim_region[Land]) || ISFILTERED(fact_abgaenge_schulart[bundesland]), CALCULATE(SUM(fact_abgaenge_schulart[anzahl]), fact_abgaenge_schulart[abschluss_key] = "ohne_hauptschulabschluss"), CALCULATE(SUM(fact_abgaenge_schulart[anzahl]), fact_abgaenge_schulart[abschluss_key] = "ohne_hauptschulabschluss", fact_abgaenge_schulart[bundesland] = "Deutschland"))
		formatString: 0
		lineageTag: b1f0c0de-1a2b-4c3d-9e8f-000000000f13

	/// LF5: Anteil einer Schulart an allen Abgaengen ohne HSA (Basis = alle Schularten im aktuellen Land-/DE-Filter), in Prozent.
	measure 'Anteil ohne HSA je Schulart %' = DIVIDE([Abgänge ohne HSA (Schulart)], CALCULATE([Abgänge ohne HSA (Schulart)], ALL(fact_abgaenge_schulart[schulart]))) * 100
		lineageTag: b1f0c0de-1a2b-4c3d-9e8f-000000000f14

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Formatierungs-Measure: LF5-Antwortchart, groesster Herkunftsbalken der Abgaenge ohne HSA (Foerderschulen) vermillion, Rest neutral.
	measure 'Farbe Schulart LF5 HSA' = IF(SELECTEDVALUE(fact_abgaenge_schulart[schulart]) = "Förderschulen", "#D55E00", "#8C8C8C")
		lineageTag: b1f0c0de-1a2b-4c3d-9e8f-000000000f15

	/// Formatierungs-Measure: LF1-Linienchart, aktuelles Schuljahr 2023/24 Okabe-Ito-Blau (#0072B2), Vorjahr 2022/23 gedaempft grau (#8C8C8C) - einheitliches Vermillion/Blau/Grau-Farbsystem im ganzen Bericht.
	measure 'Farbe Schuljahr LF1' = SWITCH(SELECTEDVALUE(dim_zeit[schuljahr]), "2023/24", "#0072B2", "2022/23", "#8C8C8C", "#8C8C8C")
		lineageTag: b1f0c0de-1a2b-4c3d-9e8f-000000000f16

	/// Formatierungs-Measure: LF8-Scatter, die drei Stadtstaaten (der Confounder) vermillion hervorgehoben, Flaechenlaender grau - vereinheitlicht LF8 mit dem Fokus/Kontext-Farbsystem statt Theme-Default Orange/Blau.
	measure 'Farbe Stadtstaat LF8' = IF(SELECTEDVALUE(dim_region[stadtstaat]) = "Stadtstaat", "#D55E00", "#8C8C8C")
		lineageTag: b1f0c0de-1a2b-4c3d-9e8f-000000000f17

	column abschluss_key
		dataType: string
		lineageTag: b309a523-0fb9-4a93-9edd-fa7a57765fc4
		summarizeBy: none
		sourceColumn: abschluss_key

	column label_regio
		dataType: string
		lineageTag: dc9a3b44-2588-4171-ae00-538af6ff57c1
		summarizeBy: none
		sourceColumn: label_regio

	column label_s09
		dataType: string
		lineageTag: 093b01f6-806d-49ee-9b51-ffbc7f690f18
		summarizeBy: none
		sourceColumn: label_s09

	column label_statbericht
		dataType: string
		lineageTag: 1ddb139c-d144-4e95-9270-8d3ea46be20a
		summarizeBy: none
		sourceColumn: label_statbericht

	column rang
		dataType: int64
		lineageTag: fc3bf54f-7f36-44ca-9b30-5c8909a550b9
		summarizeBy: none
		sourceColumn: rang

	partition dim_abschluss = m
		mode: import
		source =
				let
				typed = #table(type table [abschluss_key = text, label_regio = text, label_s09 = text, label_statbericht = text, rang = Int64.Type], {{"ohne_hauptschulabschluss", "ohne Hauptschulabschluss", "ohne Ersten Schulabschluss", "ohne Hauptschulabschluss", 1}, {"mit_hauptschulabschluss", "mit Hauptschulabschluss", "Erster Schulabschluss", "Hauptschulabschluss", 2}, {"mittlerer_abschluss", "mittlerer Abschluss", "Mittlerer Schulabschluss", "Mittlerer Abschluss", 3}, {"fachhochschulreife", "Fachhochschulreife", "Fachhochschulreife", "(n/a)", 4}, {"allgemeine_hochschulreife", "allgemeine Hochschulreife", "Allgemeine Hochschulreife", "allgemeine Hochschulreife", 5}})
				in
				typed

