table fact_abgaenge_beruflich_2023
	lineageTag: 48851c99-9a28-41f0-9539-a38b642e24f9

	column jahr
		dataType: int64
		lineageTag: 7487cb15-4ef7-4fda-9265-4a24c9bd6988
		summarizeBy: none
		sourceColumn: jahr

	column region_code
		dataType: string
		lineageTag: 331523a0-1103-4385-9a6a-a5a7e5c727d5
		summarizeBy: none
		sourceColumn: region_code

	column region
		dataType: string
		lineageTag: f5a118fd-f702-4e47-be94-4927358fbdea
		summarizeBy: none
		sourceColumn: region

	column ebene
		dataType: string
		lineageTag: dd43732f-a0f5-43e4-9df7-529b38b3aed4
		summarizeBy: none
		sourceColumn: ebene

	column bundesland_code
		dataType: string
		lineageTag: 235ca29f-77a8-47cb-9d0e-4d472e4f3b69
		summarizeBy: none
		sourceColumn: bundesland_code

	column insgesamt
		dataType: int64
		lineageTag: b8be6b1c-3ce4-4d34-9e0b-d23bca6b4869
		summarizeBy: sum
		sourceColumn: insgesamt

	column mit_hauptschulabschluss
		dataType: int64
		lineageTag: 185f0008-5ecb-4c3c-837d-b5c71c36035a
		summarizeBy: sum
		sourceColumn: mit_hauptschulabschluss

	column mit_mittlerem_abschluss
		dataType: int64
		lineageTag: 937a7994-2cd7-4b02-8c96-ea8186de2fd0
		summarizeBy: sum
		sourceColumn: mit_mittlerem_abschluss

	column fachhochschulreife
		dataType: int64
		lineageTag: 3df2c2a8-c19f-4330-9119-01c40de67a1d
		summarizeBy: sum
		sourceColumn: fachhochschulreife

	column allg_hochschulreife
		dataType: int64
		lineageTag: 9454ff23-87fa-4610-9949-5e789ffea4c8
		summarizeBy: sum
		sourceColumn: allg_hochschulreife

	partition fact_abgaenge_beruflich_2023 = m
		mode: import
		source =
				let
				src = Csv.Document(File.Contents(DataFolder & "21121-02-02-4.csv"), [Delimiter=";", Columns=15, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				y = Table.SelectRows(src, each Text.Trim([Column1]) = "2023" and fnEbene([Column2]) <> "?"),
				r = Table.AddColumn(y, "rec", each [jahr = 2023, region_code = Text.Trim([Column2]), region = Text.Trim([Column3]), ebene = fnEbene([Column2]), bundesland_code = fnBlc([Column2]), insgesamt = fnToInt([Column4]), mit_hauptschulabschluss = fnToInt([Column6]), mit_mittlerem_abschluss = fnToInt([Column8]), fachhochschulreife = fnToInt([Column10]), allg_hochschulreife = fnToInt([Column12])]),
				tbl = Table.FromRecords(r[rec]),
				typed = Table.TransformColumnTypes(tbl, {{"jahr", Int64.Type}, {"region_code", type text}, {"region", type text}, {"ebene", type text}, {"bundesland_code", type text}, {"insgesamt", Int64.Type}, {"mit_hauptschulabschluss", Int64.Type}, {"mit_mittlerem_abschluss", Int64.Type}, {"fachhochschulreife", Int64.Type}, {"allg_hochschulreife", Int64.Type}})
				in
				typed

